## Numpy array and Basic


In [3]:
import numpy as np

### creating array from list

In [9]:
arr_1d = np.array([1,2,3,4,5,])
print("1D array :", arr_1d)
arr_2d = np.array([[1,2,3],[8,9,0]])
print("2D array :", arr_2d)


1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [8 9 0]]


### List vs numpy array

In [6]:
import numpy as np
py_list = [4,5,6]
print("python list multiplication ", py_list*2) #element wise multiplication

np_array = np.array([1,2,3])
print("python list multiplication ", np_array*2)#eliment wise multiplication


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List opertaion time: ", time.time()-start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n nnumpy opertaion time: ", time.time()-start)



python list multiplication  [4, 5, 6, 4, 5, 6]
python list multiplication  [2 4 6]

 List opertaion time:  0.05824446678161621

 nnumpy opertaion time:  0.005580902099609375


## Creating Array from scratch

In [13]:
zeros = np.zeros((3,4))
print("zeors array : \n", zeros)

ones = np.ones((2,3))
print("ones :",ones)

full = np.full((2,2),7)
print("full aray: ", full)

random = np.random.random((2,4))
print("random array :\n", random)

sequence = np.arange(0,12,3)
print("sequence  array :\n", sequence)



zeors array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones : [[1. 1. 1.]
 [1. 1. 1.]]
full aray:  [[7 7]
 [7 7]]
random array :
 [[0.4267965  0.24827294 0.27588807 0.01926936]
 [0.17996907 0.613129   0.7885051  0.31442276]]
sequence  array :
 [0 3 6 9]


## Vector , Matrix and Tensor

In [16]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:",matrix)

tensor = np.array([[[4,5,6],[7,4,5]],
                   [[4,4,7],[8,2,3]]])
print("Tensor:\n",tensor)


Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor:
 [[[4 5 6]
  [7 4 5]]

 [[4 4 7]
  [8 2 3]]]


### Array properties

In [21]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Data type", arr.dtype)

shape (2, 3)
Dimension 2
Size 6
Data type int64


### Array reshaping

In [ ]:
arr = np.arange(12)
print("orignal array ",arr)

reshaped = arr.reshape(3,4)
print("\n array reshape ", reshaped)

# Return orignal array copy
flattend = reshaped.flatten()
print("flattend array",flattend)

# Revel (ruturn view, instead of copy)
raveled = reshaped.ravel()
print("raveled array", raveled)

# transpose
transpose = reshaped.T
print("transpose array ", transpose)

orignal array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 array reshape  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
