## Numpy array operation

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing",arr[3:8])
print("With step slicing",arr[2:9:2])
print("Negative  indexing",arr[-4])

Basic slicing [4 5 6 7 8]
With step slicing [3 5 7 9]
Negative  indexing 7


## For 2D array

In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire ROw",arr_2d[1])
print("Entire Col",arr_2d[:,1])

Specific element 6
Entire ROw [4 5 6]
Entire Col [2 5 8]


## Sorting

In [16]:
unsorted = np.array([3,4,5,78,7,3,5,3,1])
print("Sorted array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,4],[1,5],[8,6]])
print("Sorted 2D array by coloum ",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by Row ",np.sort(arr_2d_unsorted,axis=1))

Sorted array [ 1  3  3  3  4  5  5  7 78]
Sorted 2D array by coloum  [[1 4]
 [3 5]
 [8 6]]
Sorted 2D array by Row  [[3 4]
 [1 5]
 [6 8]]


## Filter

In [18]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers %2 ==0]
print("Even number ", even_number)

Even number  [ 2  4  6  8 10]


## Filter with mask

In [19]:
mask = numbers >5
print("Number greater than 5 ", numbers[mask])

Number greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [22]:
indices = [0,2,5]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where ", numbers[where_result])

[1 3 6]
NP where  [ 6  7  8  9 10]


In [25]:
condition_array = np.where(numbers > 5 , "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 7 8 9]


### Array compatibility

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("compatibility shapes ", a.shape == b.shape)

compatibility shapes  True


In [41]:
original = np.array([[1,3],[5,6],[8,9]])
new_row = np.array([[9,0]])
with_new_row = np.vstack((original,new_row))
print(original)
print("adding new row", with_new_row)

new_col = np.array([[4],[7],[5]])
with_new_col = np.hstack((original,new_col))
print("with_new_col", with_new_col)

[[1 3]
 [5 6]
 [8 9]]
adding new row [[1 3]
 [5 6]
 [8 9]
 [9 0]]
with_new_col [[1 3 4]
 [5 6 7]
 [8 9 5]]


In [47]:

arr = np.array([2,3,5,6,8,9,7])
deleted = np.delete(arr,2)
print("array after deletion : ",deleted)

array after deletion :  [2 3 6 8 9 7]


In [48]:
arr_2d = np.array([[2,3,5],
                   [6,8,9],
                   [7,4,1]])

deleted = np.delete(arr_2d, 1, axis=0)

print("Array after deletion:\n", deleted)

Array after deletion:
 [[2 3 5]
 [7 4 1]]
